/********* Sample code generated by the curl command line tool **********
 * All curl_easy_setopt() options are documented at:
 * http://curl.haxx.se/libcurl/c/curl_easy_setopt.html
 ************************************************************************/
#include <curl/curl.h>
#include "version.h"

int main(int argc, char *argv[])
{
    if( argc < 2 )
    {
        return 1;
    }
    CURLcode ret;
    CURL *hnd;
    struct curl_httppost *post1;
    struct curl_httppost *postend;
    struct curl_slist *slist1;

    post1 = NULL;
    postend = NULL;
    curl_formadd(&post1, &postend,
            CURLFORM_COPYNAME, "ProductName",
            CURLFORM_COPYCONTENTS, "Reaping2",
            CURLFORM_END);
    curl_formadd(&post1, &postend,
            CURLFORM_COPYNAME, "Version",
            CURLFORM_COPYCONTENTS, "\"" GIT_VERSION "-" GIT_DATE "-" GIT_REMOTE "-" GIT_BRANCH "\"",
            CURLFORM_END);
    curl_formadd(&post1, &postend,
            CURLFORM_COPYNAME, "upload_file_minidump",
            CURLFORM_FILE, argv[1],
            CURLFORM_CONTENTTYPE, "application/octet-stream",
            CURLFORM_END);
    slist1 = NULL;
    slist1 = curl_slist_append(slist1, "Host: crash-reports");

    hnd = curl_easy_init();
    curl_easy_setopt(hnd, CURLOPT_URL, "https://reaping2.dynu.net/crash-reports/submit");
    curl_easy_setopt(hnd, CURLOPT_NOPROGRESS, 1L);
    curl_easy_setopt(hnd, CURLOPT_HTTPPOST, post1);
    curl_easy_setopt(hnd, CURLOPT_USERAGENT, "curl/7.47.0");
    curl_easy_setopt(hnd, CURLOPT_HTTPHEADER, slist1);
    curl_easy_setopt(hnd, CURLOPT_MAXREDIRS, 50L);
    curl_easy_setopt(hnd, CURLOPT_HTTP_VERSION, (long)CURL_HTTP_VERSION_2TLS);
    curl_easy_setopt(hnd, CURLOPT_SSL_VERIFYPEER, 0L);
    curl_easy_setopt(hnd, CURLOPT_SSL_VERIFYHOST, 0L);
    curl_easy_setopt(hnd, CURLOPT_VERBOSE, 0L);
    curl_easy_setopt(hnd, CURLOPT_TCP_KEEPALIVE, 1L);

    /* Here is a list of options the curl code used that cannot get generated
       as source easily. You may select to either not use them or implement
       them yourself.

       CURLOPT_WRITEDATA set to a objectpointer
       CURLOPT_WRITEFUNCTION set to a functionpointer
       CURLOPT_READDATA set to a objectpointer
       CURLOPT_READFUNCTION set to a functionpointer
       CURLOPT_SEEKDATA set to a objectpointer
       CURLOPT_SEEKFUNCTION set to a functionpointer
       CURLOPT_ERRORBUFFER set to a objectpointer
       CURLOPT_STDERR set to a objectpointer
       CURLOPT_DEBUGFUNCTION set to a functionpointer
       CURLOPT_DEBUGDATA set to a objectpointer
       CURLOPT_HEADERFUNCTION set to a functionpointer
       CURLOPT_HEADERDATA set to a objectpointer

*/

    ret = curl_easy_perform(hnd);

    curl_easy_cleanup(hnd);
    hnd = NULL;
    curl_formfree(post1);
    post1 = NULL;
    curl_slist_free_all(slist1);
    slist1 = NULL;

    return (int)ret;
}
/**** End of sample code ****/
