/********* Sample code generated by the curl command line tool **********
 * All curl_easy_setopt() options are documented at:
 * http://curl.haxx.se/libcurl/c/curl_easy_setopt.html
 ************************************************************************/
#include <curl/curl.h>
#include "version.h"

int main(int argc, char *argv[])
{
    if( argc < 2 )
    {
        return 1;
    }
    CURLcode ret;
    CURL *hnd;
    struct curl_httppost *post1;
    struct curl_httppost *postend;
    struct curl_slist *slist1;

    post1 = NULL;
    postend = NULL;
    curl_formadd(&post1, &postend,
            CURLFORM_COPYNAME, "crashlog",
            CURLFORM_FILE, argv[1],
            CURLFORM_CONTENTTYPE, "application/octet-stream",
            CURLFORM_END);
    slist1 = NULL;
    slist1 = curl_slist_append(slist1, "Host: reaping2.dynu.net");

    hnd = curl_easy_init();
    curl_easy_setopt(hnd, CURLOPT_URL, "https://reaping2.dynu.net/crash-reports/api/upload");
    curl_easy_setopt(hnd, CURLOPT_NOPROGRESS, 1L);
    curl_easy_setopt(hnd, CURLOPT_HTTPPOST, post1);
    curl_easy_setopt(hnd, CURLOPT_USERAGENT, "curl/7.47.0");
    curl_easy_setopt(hnd, CURLOPT_HTTPHEADER, slist1);
    curl_easy_setopt(hnd, CURLOPT_MAXREDIRS, 50L);
    curl_easy_setopt(hnd, CURLOPT_HTTP_VERSION, (long)CURL_HTTP_VERSION_2TLS);
    curl_easy_setopt(hnd, CURLOPT_SSL_VERIFYPEER, 0L);
    curl_easy_setopt(hnd, CURLOPT_SSL_VERIFYHOST, 0L);
    curl_easy_setopt(hnd, CURLOPT_VERBOSE, 0L);
    curl_easy_setopt(hnd, CURLOPT_TCP_KEEPALIVE, 1L);

    ret = curl_easy_perform(hnd);

    curl_easy_cleanup(hnd);
    hnd = NULL;
    curl_formfree(post1);
    post1 = NULL;
    curl_slist_free_all(slist1);
    slist1 = NULL;

    return (int)ret;
}
/**** End of sample code ****/
