-- helper function collection
function setup_files_for_project(projectname)
	local matchlist = "../src/" .. projectname .. "/**.cpp"
	local outfile = io.open("../src/" .. projectname .. "_all.cpp", "w")
	print ("Setting up files for project: " .. projectname)
	outfile:write("// generated bye premake script, do not modify!\n")
	filesnames = os.matchfiles (matchlist)
	for i, filename in ipairs(filesnames) do
		local line = filename:gsub("../src/", "")
		outfile:write("#include \"" .. line .. "\"\n")
	end
	files { "../src/" .. projectname .. "/**.h", "../src/" .. projectname .. "/**.cpp", "../src/" .. projectname .. "_all.cpp" }
	configuration { "../src/" .. projectname .. "/**.cpp" }
		flags { "ExcludeFromBuild" }
end