// generated bye premake script, do not modify!
#include "render/default_model.cpp"
#include "render/model.cpp"
#include "render/model_repo.cpp"
#include "render/player_model.cpp"
#include "render/renderer.cpp"
#include "render/sprite.cpp"
#include "render/texture.cpp"
#include "render/texture_repo.cpp"
